# WORLD SET UP
NUM_AGENTS = 50
WORLD_SIZE = 30
NUM_ITERS = 100
NUM_SITES = 3 # optimal: 20
NUM_PREDS = 2
SITE_REGEN_TIME = 10
SITE_MAX_RESOURCE = 200
PADDING = 1.0
DT = 0.01

# AGENT PROPERTIES
AGENT_SENSING_RADIUS = 3
MAX_HUNGER = 100
MAX_SPEED = 5.0
AGENT_NEIGHBOR_THRESHOLD = NUM_AGENTS//10

# PREDATOR PROPERTIES
PREDATOR_SENSING_RADIUS = 5
HUNTING_MULTIPLIER = 3
PREDATOR_NEIGHBOR_THRESHOLD = 5
