# WORLD SET UP
NUM_AGENTS = 50
WORLD_SIZE = 20
NUM_ITERS = 150
NUM_SITES = 3
NUM_PREDS = 0
SITE_REGEN_TIME = 10
SITE_MAX_RESOURCE = 200
SITE_MAX_RADIUS = WORLD_SIZE * 0.25
PADDING = 0.5
DT = 0.01
NUM_GROUPS = 3
USE_BT = False

# hard code some color constants for 3 groups. will randomize later
PINK = "#FF00FF"
CYAN = "#00FFFF"
GREEN = "#B0FF00"
COLORS = {0: PINK, 1: CYAN, 2: GREEN}

# AGENT PROPERTIES
AGENT_SENSING_RADIUS = 5
MAX_HUNGER = 100
MAX_SPEED = 200.0
MAX_SITE_MEMORY = 3
MAX_NETWORK_SIZE = (NUM_AGENTS // NUM_GROUPS) + 1
AGENT_SITE_ATTRACTION = 5
# Used for base states
AGENT_NEIGHBOR_THRESHOLD = NUM_AGENTS//10
AGENT_REST_TIMER = 20
# For boids movement
AGENT_ORIENT_RADIUS = AGENT_SENSING_RADIUS // 10 if AGENT_SENSING_RADIUS // 10 > 0 else 2 # in original paper it was 8
AGENT_REPL_RADIUS = 1
K = 0.5

# PREDATOR PROPERTIES
PREDATOR_SENSING_RADIUS = 5
HUNTING_MULTIPLIER = 3
PREDATOR_NEIGHBOR_THRESHOLD = 5
